openapi: 3.0.0
info:
  version: 2.0.0
  title: Easy Marketplace API
  description: Bem vindo à nossa API
  termsOfService: termos
  contact:
    name: Contato
    url: http://localhost:8080
    email: www.diegosantos.com.br@gmail.com
  license:
    name: FREE
    url: http://localhost:8080
  
servers:
  - url: https://localhost:8080
    description: Servidor de desenvolvimento
paths:
  /auth/login:
    post:
      summary: Obter token de acesso para autorização
      description: Retorna um token de acesso
      responses:
        200:
          description: Retorna um token de acesso válido
          content:
            application/json:
              schema:
                type: string
                example: {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlYXN5LW1hcmtldHBsYWNlLWFwaSIsInN1YiI6ImNqc2dpeXR3ODAwMXplbndnOGZvN2RsN2UiLCJpYXQiOjE1Njg2MDM1MjYsImV4cCI6MTU2ODYwNzEyNn0.qfYdPRRGY04pVpMwDRN4sD3imvR8HFC34hXUuNMqCww"}
        500:
          description: Erro interno
        401:
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Credenciais inválidas"}
        405:
          description: Método HTTP não permitido
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Método HTTP não permitido"}
        422:
          description: Erro de validação dos parâmetros
          content:
            application/json:
              schema:
                type: string
                example : {
                    "email": [
                      "The email field is required."
                    ],
                    "password": [
                      "The password field is required."
                    ]
                  }
      parameters: 
        - in: query
          name: email
          required: true
          schema:
            type: string
          description: O e-mail do usuário
        - in: query
          name: password
          required: true
          schema:
            type: string
          description: A senha do usuário
  /api/services:
    get:
      summary: Usuário solicita serviço
      description: Retorna um resumo do score do fornecedor
      responses:
        200:
          description: Retorna o serviço mais próximo dentro do raio de 10km
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partners"
        500:
          description: Erro interno
        400:
          description: Token fornecido expirou
          content:
            application/json:
              schema:
                type: string
                example : {"error": "O token fornecido expirou"}
        401:
          description: Acesso não autorizado
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Acesso não autorizado"}
        404:
          description: Nenhum serviço disponível próximo ao endereço informado
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Nenhum serviço disponível próximo ao endereço informado"}
        405:
          description: Método HTTP não permitido
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Método HTTP não permitido"}
        422:
          description: Erro de validação dos parâmetros
          content:
            application/json:
              schema:
                type: string
                example: {
                  "lat": [
                    "The lat field is required."
                  ],
                  "long": [
                    "The long field is required."
                  ]
                }
      parameters: 
        - in: header
          name: Token
          required: true
          schema:
            type: string
          description: O token de acesso do usuário
        - in: query
          name: lat
          required: true
          schema:
            type: string
          description: A latitude do endereço do usuário
        - in: query
          name: long
          required: true
          schema:
            type: string
          description: A longitude do endereço do usuário
        - in: query
          name: services
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
               - 'OIL_CHANGE'
               - 'DRY_WASHING'
          description: O serviço solicitado pelo usuário
  
  /api/partner/availables:
    get:
      summary: Lista os profissionais disponíveis
      description: Profissionais com serviços disponíveis no endereço informado
      responses:
        200:
          description: Retorna uma lista dos profissionais disponíveis dentro de um raio de distância informado, o default é de 10km
          content:
            application/json:
              schema:
                type: object
                properties:
                  partners:
                    type: array
                    items:
                      $ref: "#/components/schemas/Partners"
        500:
          description: Erro interno
        400:
          description: Token fornecido expirou
          content:
            application/json:
              schema:
                type: string
                example : {"error": "O token fornecido expirou"}
        401:
          description: Acesso não autorizado
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Acesso não autorizado"}
        405:
          description: Método HTTP não permitido
          content:
            application/json:
              schema:
                type: string
                example : {"error": "Método HTTP não permitido"}
        422:
          description: Erro de validação dos parâmetros
          content:
            application/json:
              schema:
                type: string
                example: {
                  "address": [
                    "The address field is required."
                  ]
                }
      parameters: 
        - in: header
          name: Token
          required: true
          schema:
            type: string
          description: Seu token de acesso válido
        - in: query
          name: address
          schema:
            type: string
          description: O endereço do usuário
        - in: query
          name: area
          schema:
            type: integer
            default: 10
          description: A área de disponibilidade dos serviços (Km)

components:
  schemas:
    Partners:
      type: object
      properties:
        name:
          type: string
          description: O nome do parceiro
        services:
          type: string
          description: Os serviços que o parceiro executa
        address:
          type: string
          description: O endereço do parceiro
        distance:
          type: string
          description: A distância até o parceiro que fornece o(s) serviço(s)
       
          
            
          
    

    