#!/bin/bash
docker-compose build && 
docker-compose start && 
docker exec -i easy-php-fpm php7.3 composer.phar install && 
cp .env-example .env &&
docker exec -i easy-php-fpm php7.3 artisan install:app